apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
        - name: my-python-app
          image: gcr.io/primeval-creek-424606-j8/my-python-app:latest  
          ports:
            - containerPort: 5000  
          env:
            - name: ENV_VAR_NAME  
              value: "value"

